name:         vorbis
version:      0.0.0
author:       Herman Bergwerf <hermanbergwerf@gmail.com>
description:  OGG Vorbis decoder
homepage:     https://github.com/hermanbergwerf/dart-vorbis
environment:
  sdk:        '>=1.8.0 <2.0.0'
